name: Spotify daily monitor

on: 
  workflow_dispatch


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute test cases
        env:
            SPOTIFY_USER: ${{ secrets.SPOTIFY_USER }}
            SPOTIFY_PASSWORD: ${{ secrets.SPOTIFY_USER_KEY }}
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" pytest --alluredir=allure-results
        continue-on-error: true
        
      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline --save-dev
          allure generate allure-results --clean -o allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
