name: Spotify daily monitor

on: 
  workflow_dispatch
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Chromedriver
        uses: nanasess/setup-chromedriver@v2
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute test cases
        run: pytest
